server:
  port: 8081

spring:
  data:
    mongodb:
      uri:
        database:mongodb://localhost:27017/userdb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true


logging:
  level:
    root: INFO
    com.ecommerce.user1: TRACE

  file:
    name: log/${spring.application.name}.log

  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
